name: FMI Server

on:
  repository_dispatch:
    types: [start_server]

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, mbstring, json

      - name: Start PHP Server
        run: |
          nohup php -S 0.0.0.0:3000 -t . > server.log 2>&1 &
          echo "PHP server started on port 3000"

      - name: Start ngrok
        uses: P3TERX/ngrok-action@v1
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
          port: 3000
          region: us

      - name: Wait for request
        run: |
          sleep 30  # انتظر الطلب
